spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./database.db
  web:
    resources:
      static-locations: classpath:/static/
app:
  filter-group-regex:
    - "更新时间"
    - "•温馨「提示」"
  group-mapping:
    "[央视台]":
      - ".*央视.*"
    "[卫视台]":
      - ".*卫视.*"
    "[数字台]":
      - ".*IHOT.*"
      - ".*iHOT.*"
      - ".*NewTV.*"
      - "•咪咕「网·Ⅰ」"
      - "•咪咕「网·Ⅱ」"
      - "•数字「IPV6」"
      - "咪咕直播"
      - "埋堆堆"
      - "数字轮播"
      - "数字频道"
    "[地方台]":
      - ".*地方.*"
      - "•地区「IPV6」"
      - "湖南台"
      - "上海频道"
    "[体育台]":
      - ".*体育.*"
    "[电影]":
      - "电影轮播"
      - "电影频道"
    "[电视剧]":
      - "电视剧轮播"
    "[游戏]":
      - "游戏频道"
    "[记录]":
      - "纪录频道"
    "[儿童]":
      - ".*儿童.*"
      - ".*动画.*"
    "[4K]":
      - "4K"
      - "•4K「IPV6」"
    "[历年春晚]":
      - "历年春晚"
      - "春晚频道"
    "[港澳台]":
      - "港澳台AKTV"
      - "港澳台频道"
      - "港澳频道"
    "[国际台]":
      - "国际频道"
    "[其他]":
      - "综艺频道"
      - "其他频道"
      - "戏曲频道"
      - "优质个源"
  title-mapping:
    "[CCTV-1]":
      - "CCTV1[^0-9].*"
      - "CCTV 1[^0-9].*"
      - "CCTV-1[^0-9].*"
    "[CCTV-2]":
      - "CCTV2.*"
      - "CCTV 2.*"
      - "CCTV-2.*"
    "[CCTV-3]":
      - "CCTV3.*"
      - "CCTV 3.*"
      - "CCTV-3.*"
    "[CCTV-4]":
      - "CCTV4"
      - "CCTV4[^K].*"
      - "CCTV 4[^K].*"
      - "CCTV-4[^K].*"
    "[CCTV-4K]":
      - "CCTV4K"
      - "CCTV 4K.*"
      - "CCTV-4K.*"
    "[CCTV-5]":
      - "CCTV5"
      - "CCTV5[^\\+].*"
      - "CCTV 5[^\\+].*"
      - "CCTV-5[^\\+].*"
    "[CCTV-5+]":
      - "CCTV5\\+.*"
      - "CCTV 5\\+.*"
      - "CCTV-5\\+.*"
    "[CCTV-6]":
      - "CCTV6.*"
      - "CCTV 6.*"
      - "CCTV-6.*"
    "[CCTV-7]":
      - "CCTV7.*"
      - "CCTV 7.*"
      - "CCTV-7.*"
    "[CCTV-8]":
      - "CCTV8.*"
      - "CCTV 8.*"
      - "CCTV-8.*"
    "[CCTV-9]":
      - "CCTV9.*"
      - "CCTV 9.*"
      - "CCTV-9.*"
    "[CCTV-10]":
      - "CCTV10.*"
      - "CCTV 10.*"
      - "CCTV-10.*"
    "[CCTV-11]":
      - "CCTV11.*"
      - "CCTV 11.*"
      - "CCTV-11.*"
    "[CCTV-12]":
      - "CCTV12.*"
      - "CCTV 12.*"
      - "CCTV-12.*"
    "[CCTV-13]":
      - "CCTV13.*"
      - "CCTV 13.*"
      - "CCTV-13.*"
    "[CCTV-14]":
      - "CCTV14.*"
      - "CCTV 14.*"
      - "CCTV-14.*"
    "[CCTV-15]":
      - "CCTV15.*"
      - "CCTV 15.*"
      - "CCTV-15.*"
    "[CCTV-16]":
      - "CCTV16.*"
      - "CCTV 16.*"
      - "CCTV-16.*"
    "[CCTV-17]":
      - "CCTV17.*"
      - "CCTV 17.*"
      - "CCTV-17.*"
  title2-group-mapping:
    "[儿童]":
      - ".*卡通.*"
    "[记录]":
      - ".*求索.*"
      - ".*纪实.*"
  remove-chars:
    - "IPV6"
    - "「"
    - "」"