name: Update M3U Files

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: centos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy M3U files
        run: |
          cp ../*.m3u ./

      - name: Commit and push changes
        run: |
          git config --local user.name "Allen Hu"
          git config --local user.email "huxiao.mail@qq.com"
          git pull
          git add *.m3u
          git commit -m "Update M3U files automatically" || echo "No changes to commit"
          git push